name: Run Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'Lemurian'

    # Step 3: Download and set up ChromeDriver
    - name: Set up ChromeDriver
      uses: nanas/setup-chromedriver@v1
      with:
        version: latest

    # Step 4: Set up Selenium dependencies
    - name: Install Maven
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'Lemurian'

    # Step 5: Build the project using Maven
    - name: Build with Maven
      run: maven compile

    # Step 6: Run the Selenium test
    - name: Run Selenium Test
      run: |
        maven test
